workflows:
  android-workflow:
    name: Professor X APK
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Install Gradle
        script: |
          apt-get install -y gradle || true
      - name: Build APK
        script: |
          gradle assembleRelease --warning-mode all
    artifacts:
      - app/build/outputs/apk/release/*.apk
